theme = "ayu_evolve"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "╎"

[editor.whitespace.render]
space = "all"

[editor.whitespace.characters]
space = "·"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
